# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bao1/rtpaudio

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bao1/rtpaudio

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/bao1/rtpaudio/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bao1/rtpaudio/CMakeFiles /home/bao1/rtpaudio/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bao1/rtpaudio/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dist

# Build rule for target.
dist: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dist
.PHONY : dist

# fast build rule for target.
dist/fast:
	$(MAKE) -f CMakeFiles/dist.dir/build.make CMakeFiles/dist.dir/build
.PHONY : dist/fast

#=============================================================================
# Target rules for targets named mpegsound

# Build rule for target.
mpegsound: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mpegsound
.PHONY : mpegsound

# fast build rule for target.
mpegsound/fast:
	$(MAKE) -f libmpegsound/CMakeFiles/mpegsound.dir/build.make libmpegsound/CMakeFiles/mpegsound.dir/build
.PHONY : mpegsound/fast

# Manual pre-install relink rule for target.
mpegsound/preinstall:
	$(MAKE) -f libmpegsound/CMakeFiles/mpegsound.dir/build.make libmpegsound/CMakeFiles/mpegsound.dir/preinstall
.PHONY : mpegsound/preinstall

#=============================================================================
# Target rules for targets named mpegsound-static

# Build rule for target.
mpegsound-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mpegsound-static
.PHONY : mpegsound-static

# fast build rule for target.
mpegsound-static/fast:
	$(MAKE) -f libmpegsound/CMakeFiles/mpegsound-static.dir/build.make libmpegsound/CMakeFiles/mpegsound-static.dir/build
.PHONY : mpegsound-static/fast

#=============================================================================
# Target rules for targets named mpegsound_automoc

# Build rule for target.
mpegsound_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mpegsound_automoc
.PHONY : mpegsound_automoc

# fast build rule for target.
mpegsound_automoc/fast:
	$(MAKE) -f libmpegsound/CMakeFiles/mpegsound_automoc.dir/build.make libmpegsound/CMakeFiles/mpegsound_automoc.dir/build
.PHONY : mpegsound_automoc/fast

#=============================================================================
# Target rules for targets named mpegsound-static_automoc

# Build rule for target.
mpegsound-static_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mpegsound-static_automoc
.PHONY : mpegsound-static_automoc

# fast build rule for target.
mpegsound-static_automoc/fast:
	$(MAKE) -f libmpegsound/CMakeFiles/mpegsound-static_automoc.dir/build.make libmpegsound/CMakeFiles/mpegsound-static_automoc.dir/build
.PHONY : mpegsound-static_automoc/fast

#=============================================================================
# Target rules for targets named rtpa-client

# Build rule for target.
rtpa-client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtpa-client
.PHONY : rtpa-client

# fast build rule for target.
rtpa-client/fast:
	$(MAKE) -f src/CMakeFiles/rtpa-client.dir/build.make src/CMakeFiles/rtpa-client.dir/build
.PHONY : rtpa-client/fast

# Manual pre-install relink rule for target.
rtpa-client/preinstall:
	$(MAKE) -f src/CMakeFiles/rtpa-client.dir/build.make src/CMakeFiles/rtpa-client.dir/preinstall
.PHONY : rtpa-client/preinstall

#=============================================================================
# Target rules for targets named rtpa-server

# Build rule for target.
rtpa-server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtpa-server
.PHONY : rtpa-server

# fast build rule for target.
rtpa-server/fast:
	$(MAKE) -f src/CMakeFiles/rtpa-server.dir/build.make src/CMakeFiles/rtpa-server.dir/build
.PHONY : rtpa-server/fast

# Manual pre-install relink rule for target.
rtpa-server/preinstall:
	$(MAKE) -f src/CMakeFiles/rtpa-server.dir/build.make src/CMakeFiles/rtpa-server.dir/preinstall
.PHONY : rtpa-server/preinstall

#=============================================================================
# Target rules for targets named qosmgr-static

# Build rule for target.
qosmgr-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qosmgr-static
.PHONY : qosmgr-static

# fast build rule for target.
qosmgr-static/fast:
	$(MAKE) -f src/CMakeFiles/qosmgr-static.dir/build.make src/CMakeFiles/qosmgr-static.dir/build
.PHONY : qosmgr-static/fast

#=============================================================================
# Target rules for targets named rtpaudioclient-static

# Build rule for target.
rtpaudioclient-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtpaudioclient-static
.PHONY : rtpaudioclient-static

# fast build rule for target.
rtpaudioclient-static/fast:
	$(MAKE) -f src/CMakeFiles/rtpaudioclient-static.dir/build.make src/CMakeFiles/rtpaudioclient-static.dir/build
.PHONY : rtpaudioclient-static/fast

#=============================================================================
# Target rules for targets named rtpa-vclient

# Build rule for target.
rtpa-vclient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtpa-vclient
.PHONY : rtpa-vclient

# fast build rule for target.
rtpa-vclient/fast:
	$(MAKE) -f src/CMakeFiles/rtpa-vclient.dir/build.make src/CMakeFiles/rtpa-vclient.dir/build
.PHONY : rtpa-vclient/fast

# Manual pre-install relink rule for target.
rtpa-vclient/preinstall:
	$(MAKE) -f src/CMakeFiles/rtpa-vclient.dir/build.make src/CMakeFiles/rtpa-vclient.dir/preinstall
.PHONY : rtpa-vclient/preinstall

#=============================================================================
# Target rules for targets named rtpaudioclient

# Build rule for target.
rtpaudioclient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtpaudioclient
.PHONY : rtpaudioclient

# fast build rule for target.
rtpaudioclient/fast:
	$(MAKE) -f src/CMakeFiles/rtpaudioclient.dir/build.make src/CMakeFiles/rtpaudioclient.dir/build
.PHONY : rtpaudioclient/fast

# Manual pre-install relink rule for target.
rtpaudioclient/preinstall:
	$(MAKE) -f src/CMakeFiles/rtpaudioclient.dir/build.make src/CMakeFiles/rtpaudioclient.dir/preinstall
.PHONY : rtpaudioclient/preinstall

#=============================================================================
# Target rules for targets named rtpaudioserver-static

# Build rule for target.
rtpaudioserver-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtpaudioserver-static
.PHONY : rtpaudioserver-static

# fast build rule for target.
rtpaudioserver-static/fast:
	$(MAKE) -f src/CMakeFiles/rtpaudioserver-static.dir/build.make src/CMakeFiles/rtpaudioserver-static.dir/build
.PHONY : rtpaudioserver-static/fast

#=============================================================================
# Target rules for targets named rtpaudioserver

# Build rule for target.
rtpaudioserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtpaudioserver
.PHONY : rtpaudioserver

# fast build rule for target.
rtpaudioserver/fast:
	$(MAKE) -f src/CMakeFiles/rtpaudioserver.dir/build.make src/CMakeFiles/rtpaudioserver.dir/build
.PHONY : rtpaudioserver/fast

# Manual pre-install relink rule for target.
rtpaudioserver/preinstall:
	$(MAKE) -f src/CMakeFiles/rtpaudioserver.dir/build.make src/CMakeFiles/rtpaudioserver.dir/preinstall
.PHONY : rtpaudioserver/preinstall

#=============================================================================
# Target rules for targets named rtpaudiocommon-static

# Build rule for target.
rtpaudiocommon-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtpaudiocommon-static
.PHONY : rtpaudiocommon-static

# fast build rule for target.
rtpaudiocommon-static/fast:
	$(MAKE) -f src/CMakeFiles/rtpaudiocommon-static.dir/build.make src/CMakeFiles/rtpaudiocommon-static.dir/build
.PHONY : rtpaudiocommon-static/fast

#=============================================================================
# Target rules for targets named audiowriter-static

# Build rule for target.
audiowriter-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 audiowriter-static
.PHONY : audiowriter-static

# fast build rule for target.
audiowriter-static/fast:
	$(MAKE) -f src/CMakeFiles/audiowriter-static.dir/build.make src/CMakeFiles/audiowriter-static.dir/build
.PHONY : audiowriter-static/fast

#=============================================================================
# Target rules for targets named rtpserver

# Build rule for target.
rtpserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtpserver
.PHONY : rtpserver

# fast build rule for target.
rtpserver/fast:
	$(MAKE) -f src/CMakeFiles/rtpserver.dir/build.make src/CMakeFiles/rtpserver.dir/build
.PHONY : rtpserver/fast

# Manual pre-install relink rule for target.
rtpserver/preinstall:
	$(MAKE) -f src/CMakeFiles/rtpserver.dir/build.make src/CMakeFiles/rtpserver.dir/preinstall
.PHONY : rtpserver/preinstall

#=============================================================================
# Target rules for targets named audiowriter

# Build rule for target.
audiowriter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 audiowriter
.PHONY : audiowriter

# fast build rule for target.
audiowriter/fast:
	$(MAKE) -f src/CMakeFiles/audiowriter.dir/build.make src/CMakeFiles/audiowriter.dir/build
.PHONY : audiowriter/fast

# Manual pre-install relink rule for target.
audiowriter/preinstall:
	$(MAKE) -f src/CMakeFiles/audiowriter.dir/build.make src/CMakeFiles/audiowriter.dir/preinstall
.PHONY : audiowriter/preinstall

#=============================================================================
# Target rules for targets named audioreader

# Build rule for target.
audioreader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 audioreader
.PHONY : audioreader

# fast build rule for target.
audioreader/fast:
	$(MAKE) -f src/CMakeFiles/audioreader.dir/build.make src/CMakeFiles/audioreader.dir/build
.PHONY : audioreader/fast

# Manual pre-install relink rule for target.
audioreader/preinstall:
	$(MAKE) -f src/CMakeFiles/audioreader.dir/build.make src/CMakeFiles/audioreader.dir/preinstall
.PHONY : audioreader/preinstall

#=============================================================================
# Target rules for targets named audiodecoder-static

# Build rule for target.
audiodecoder-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 audiodecoder-static
.PHONY : audiodecoder-static

# fast build rule for target.
audiodecoder-static/fast:
	$(MAKE) -f src/CMakeFiles/audiodecoder-static.dir/build.make src/CMakeFiles/audiodecoder-static.dir/build
.PHONY : audiodecoder-static/fast

#=============================================================================
# Target rules for targets named rtpaudiocommon

# Build rule for target.
rtpaudiocommon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtpaudiocommon
.PHONY : rtpaudiocommon

# fast build rule for target.
rtpaudiocommon/fast:
	$(MAKE) -f src/CMakeFiles/rtpaudiocommon.dir/build.make src/CMakeFiles/rtpaudiocommon.dir/build
.PHONY : rtpaudiocommon/fast

# Manual pre-install relink rule for target.
rtpaudiocommon/preinstall:
	$(MAKE) -f src/CMakeFiles/rtpaudiocommon.dir/build.make src/CMakeFiles/rtpaudiocommon.dir/preinstall
.PHONY : rtpaudiocommon/preinstall

#=============================================================================
# Target rules for targets named tdtoolbox

# Build rule for target.
tdtoolbox: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tdtoolbox
.PHONY : tdtoolbox

# fast build rule for target.
tdtoolbox/fast:
	$(MAKE) -f src/CMakeFiles/tdtoolbox.dir/build.make src/CMakeFiles/tdtoolbox.dir/build
.PHONY : tdtoolbox/fast

# Manual pre-install relink rule for target.
tdtoolbox/preinstall:
	$(MAKE) -f src/CMakeFiles/tdtoolbox.dir/build.make src/CMakeFiles/tdtoolbox.dir/preinstall
.PHONY : tdtoolbox/preinstall

#=============================================================================
# Target rules for targets named audiocommon-static

# Build rule for target.
audiocommon-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 audiocommon-static
.PHONY : audiocommon-static

# fast build rule for target.
audiocommon-static/fast:
	$(MAKE) -f src/CMakeFiles/audiocommon-static.dir/build.make src/CMakeFiles/audiocommon-static.dir/build
.PHONY : audiocommon-static/fast

#=============================================================================
# Target rules for targets named rtpclient-static

# Build rule for target.
rtpclient-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtpclient-static
.PHONY : rtpclient-static

# fast build rule for target.
rtpclient-static/fast:
	$(MAKE) -f src/CMakeFiles/rtpclient-static.dir/build.make src/CMakeFiles/rtpclient-static.dir/build
.PHONY : rtpclient-static/fast

#=============================================================================
# Target rules for targets named rtpa-qclient

# Build rule for target.
rtpa-qclient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtpa-qclient
.PHONY : rtpa-qclient

# fast build rule for target.
rtpa-qclient/fast:
	$(MAKE) -f src/CMakeFiles/rtpa-qclient.dir/build.make src/CMakeFiles/rtpa-qclient.dir/build
.PHONY : rtpa-qclient/fast

# Manual pre-install relink rule for target.
rtpa-qclient/preinstall:
	$(MAKE) -f src/CMakeFiles/rtpa-qclient.dir/build.make src/CMakeFiles/rtpa-qclient.dir/preinstall
.PHONY : rtpa-qclient/preinstall

#=============================================================================
# Target rules for targets named mediainfo

# Build rule for target.
mediainfo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mediainfo
.PHONY : mediainfo

# fast build rule for target.
mediainfo/fast:
	$(MAKE) -f src/CMakeFiles/mediainfo.dir/build.make src/CMakeFiles/mediainfo.dir/build
.PHONY : mediainfo/fast

# Manual pre-install relink rule for target.
mediainfo/preinstall:
	$(MAKE) -f src/CMakeFiles/mediainfo.dir/build.make src/CMakeFiles/mediainfo.dir/preinstall
.PHONY : mediainfo/preinstall

#=============================================================================
# Target rules for targets named audiocodeccommon-static

# Build rule for target.
audiocodeccommon-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 audiocodeccommon-static
.PHONY : audiocodeccommon-static

# fast build rule for target.
audiocodeccommon-static/fast:
	$(MAKE) -f src/CMakeFiles/audiocodeccommon-static.dir/build.make src/CMakeFiles/audiocodeccommon-static.dir/build
.PHONY : audiocodeccommon-static/fast

#=============================================================================
# Target rules for targets named mediainfo-static

# Build rule for target.
mediainfo-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mediainfo-static
.PHONY : mediainfo-static

# fast build rule for target.
mediainfo-static/fast:
	$(MAKE) -f src/CMakeFiles/mediainfo-static.dir/build.make src/CMakeFiles/mediainfo-static.dir/build
.PHONY : mediainfo-static/fast

#=============================================================================
# Target rules for targets named rtpcommon-static

# Build rule for target.
rtpcommon-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtpcommon-static
.PHONY : rtpcommon-static

# fast build rule for target.
rtpcommon-static/fast:
	$(MAKE) -f src/CMakeFiles/rtpcommon-static.dir/build.make src/CMakeFiles/rtpcommon-static.dir/build
.PHONY : rtpcommon-static/fast

#=============================================================================
# Target rules for targets named rtpserver-static

# Build rule for target.
rtpserver-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtpserver-static
.PHONY : rtpserver-static

# fast build rule for target.
rtpserver-static/fast:
	$(MAKE) -f src/CMakeFiles/rtpserver-static.dir/build.make src/CMakeFiles/rtpserver-static.dir/build
.PHONY : rtpserver-static/fast

#=============================================================================
# Target rules for targets named audioencoder-static

# Build rule for target.
audioencoder-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 audioencoder-static
.PHONY : audioencoder-static

# fast build rule for target.
audioencoder-static/fast:
	$(MAKE) -f src/CMakeFiles/audioencoder-static.dir/build.make src/CMakeFiles/audioencoder-static.dir/build
.PHONY : audioencoder-static/fast

#=============================================================================
# Target rules for targets named rtpcommon

# Build rule for target.
rtpcommon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtpcommon
.PHONY : rtpcommon

# fast build rule for target.
rtpcommon/fast:
	$(MAKE) -f src/CMakeFiles/rtpcommon.dir/build.make src/CMakeFiles/rtpcommon.dir/build
.PHONY : rtpcommon/fast

# Manual pre-install relink rule for target.
rtpcommon/preinstall:
	$(MAKE) -f src/CMakeFiles/rtpcommon.dir/build.make src/CMakeFiles/rtpcommon.dir/preinstall
.PHONY : rtpcommon/preinstall

#=============================================================================
# Target rules for targets named rtpclient

# Build rule for target.
rtpclient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtpclient
.PHONY : rtpclient

# fast build rule for target.
rtpclient/fast:
	$(MAKE) -f src/CMakeFiles/rtpclient.dir/build.make src/CMakeFiles/rtpclient.dir/build
.PHONY : rtpclient/fast

# Manual pre-install relink rule for target.
rtpclient/preinstall:
	$(MAKE) -f src/CMakeFiles/rtpclient.dir/build.make src/CMakeFiles/rtpclient.dir/preinstall
.PHONY : rtpclient/preinstall

#=============================================================================
# Target rules for targets named audiocodeccommon

# Build rule for target.
audiocodeccommon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 audiocodeccommon
.PHONY : audiocodeccommon

# fast build rule for target.
audiocodeccommon/fast:
	$(MAKE) -f src/CMakeFiles/audiocodeccommon.dir/build.make src/CMakeFiles/audiocodeccommon.dir/build
.PHONY : audiocodeccommon/fast

# Manual pre-install relink rule for target.
audiocodeccommon/preinstall:
	$(MAKE) -f src/CMakeFiles/audiocodeccommon.dir/build.make src/CMakeFiles/audiocodeccommon.dir/preinstall
.PHONY : audiocodeccommon/preinstall

#=============================================================================
# Target rules for targets named audioreader-static

# Build rule for target.
audioreader-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 audioreader-static
.PHONY : audioreader-static

# fast build rule for target.
audioreader-static/fast:
	$(MAKE) -f src/CMakeFiles/audioreader-static.dir/build.make src/CMakeFiles/audioreader-static.dir/build
.PHONY : audioreader-static/fast

#=============================================================================
# Target rules for targets named audioencoder

# Build rule for target.
audioencoder: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 audioencoder
.PHONY : audioencoder

# fast build rule for target.
audioencoder/fast:
	$(MAKE) -f src/CMakeFiles/audioencoder.dir/build.make src/CMakeFiles/audioencoder.dir/build
.PHONY : audioencoder/fast

# Manual pre-install relink rule for target.
audioencoder/preinstall:
	$(MAKE) -f src/CMakeFiles/audioencoder.dir/build.make src/CMakeFiles/audioencoder.dir/preinstall
.PHONY : audioencoder/preinstall

#=============================================================================
# Target rules for targets named qosmgr

# Build rule for target.
qosmgr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qosmgr
.PHONY : qosmgr

# fast build rule for target.
qosmgr/fast:
	$(MAKE) -f src/CMakeFiles/qosmgr.dir/build.make src/CMakeFiles/qosmgr.dir/build
.PHONY : qosmgr/fast

# Manual pre-install relink rule for target.
qosmgr/preinstall:
	$(MAKE) -f src/CMakeFiles/qosmgr.dir/build.make src/CMakeFiles/qosmgr.dir/preinstall
.PHONY : qosmgr/preinstall

#=============================================================================
# Target rules for targets named tdtoolbox-static

# Build rule for target.
tdtoolbox-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tdtoolbox-static
.PHONY : tdtoolbox-static

# fast build rule for target.
tdtoolbox-static/fast:
	$(MAKE) -f src/CMakeFiles/tdtoolbox-static.dir/build.make src/CMakeFiles/tdtoolbox-static.dir/build
.PHONY : tdtoolbox-static/fast

#=============================================================================
# Target rules for targets named audiocommon

# Build rule for target.
audiocommon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 audiocommon
.PHONY : audiocommon

# fast build rule for target.
audiocommon/fast:
	$(MAKE) -f src/CMakeFiles/audiocommon.dir/build.make src/CMakeFiles/audiocommon.dir/build
.PHONY : audiocommon/fast

# Manual pre-install relink rule for target.
audiocommon/preinstall:
	$(MAKE) -f src/CMakeFiles/audiocommon.dir/build.make src/CMakeFiles/audiocommon.dir/preinstall
.PHONY : audiocommon/preinstall

#=============================================================================
# Target rules for targets named audiodecoder

# Build rule for target.
audiodecoder: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 audiodecoder
.PHONY : audiodecoder

# fast build rule for target.
audiodecoder/fast:
	$(MAKE) -f src/CMakeFiles/audiodecoder.dir/build.make src/CMakeFiles/audiodecoder.dir/build
.PHONY : audiodecoder/fast

# Manual pre-install relink rule for target.
audiodecoder/preinstall:
	$(MAKE) -f src/CMakeFiles/audiodecoder.dir/build.make src/CMakeFiles/audiodecoder.dir/preinstall
.PHONY : audiodecoder/preinstall

#=============================================================================
# Target rules for targets named rtpa-client_automoc

# Build rule for target.
rtpa-client_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtpa-client_automoc
.PHONY : rtpa-client_automoc

# fast build rule for target.
rtpa-client_automoc/fast:
	$(MAKE) -f src/CMakeFiles/rtpa-client_automoc.dir/build.make src/CMakeFiles/rtpa-client_automoc.dir/build
.PHONY : rtpa-client_automoc/fast

#=============================================================================
# Target rules for targets named rtpa-server_automoc

# Build rule for target.
rtpa-server_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtpa-server_automoc
.PHONY : rtpa-server_automoc

# fast build rule for target.
rtpa-server_automoc/fast:
	$(MAKE) -f src/CMakeFiles/rtpa-server_automoc.dir/build.make src/CMakeFiles/rtpa-server_automoc.dir/build
.PHONY : rtpa-server_automoc/fast

#=============================================================================
# Target rules for targets named qosmgr-static_automoc

# Build rule for target.
qosmgr-static_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qosmgr-static_automoc
.PHONY : qosmgr-static_automoc

# fast build rule for target.
qosmgr-static_automoc/fast:
	$(MAKE) -f src/CMakeFiles/qosmgr-static_automoc.dir/build.make src/CMakeFiles/qosmgr-static_automoc.dir/build
.PHONY : qosmgr-static_automoc/fast

#=============================================================================
# Target rules for targets named rtpaudioclient-static_automoc

# Build rule for target.
rtpaudioclient-static_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtpaudioclient-static_automoc
.PHONY : rtpaudioclient-static_automoc

# fast build rule for target.
rtpaudioclient-static_automoc/fast:
	$(MAKE) -f src/CMakeFiles/rtpaudioclient-static_automoc.dir/build.make src/CMakeFiles/rtpaudioclient-static_automoc.dir/build
.PHONY : rtpaudioclient-static_automoc/fast

#=============================================================================
# Target rules for targets named rtpa-vclient_automoc

# Build rule for target.
rtpa-vclient_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtpa-vclient_automoc
.PHONY : rtpa-vclient_automoc

# fast build rule for target.
rtpa-vclient_automoc/fast:
	$(MAKE) -f src/CMakeFiles/rtpa-vclient_automoc.dir/build.make src/CMakeFiles/rtpa-vclient_automoc.dir/build
.PHONY : rtpa-vclient_automoc/fast

#=============================================================================
# Target rules for targets named rtpaudioclient_automoc

# Build rule for target.
rtpaudioclient_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtpaudioclient_automoc
.PHONY : rtpaudioclient_automoc

# fast build rule for target.
rtpaudioclient_automoc/fast:
	$(MAKE) -f src/CMakeFiles/rtpaudioclient_automoc.dir/build.make src/CMakeFiles/rtpaudioclient_automoc.dir/build
.PHONY : rtpaudioclient_automoc/fast

#=============================================================================
# Target rules for targets named rtpaudioserver-static_automoc

# Build rule for target.
rtpaudioserver-static_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtpaudioserver-static_automoc
.PHONY : rtpaudioserver-static_automoc

# fast build rule for target.
rtpaudioserver-static_automoc/fast:
	$(MAKE) -f src/CMakeFiles/rtpaudioserver-static_automoc.dir/build.make src/CMakeFiles/rtpaudioserver-static_automoc.dir/build
.PHONY : rtpaudioserver-static_automoc/fast

#=============================================================================
# Target rules for targets named rtpaudioserver_automoc

# Build rule for target.
rtpaudioserver_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtpaudioserver_automoc
.PHONY : rtpaudioserver_automoc

# fast build rule for target.
rtpaudioserver_automoc/fast:
	$(MAKE) -f src/CMakeFiles/rtpaudioserver_automoc.dir/build.make src/CMakeFiles/rtpaudioserver_automoc.dir/build
.PHONY : rtpaudioserver_automoc/fast

#=============================================================================
# Target rules for targets named rtpaudiocommon-static_automoc

# Build rule for target.
rtpaudiocommon-static_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtpaudiocommon-static_automoc
.PHONY : rtpaudiocommon-static_automoc

# fast build rule for target.
rtpaudiocommon-static_automoc/fast:
	$(MAKE) -f src/CMakeFiles/rtpaudiocommon-static_automoc.dir/build.make src/CMakeFiles/rtpaudiocommon-static_automoc.dir/build
.PHONY : rtpaudiocommon-static_automoc/fast

#=============================================================================
# Target rules for targets named audiowriter-static_automoc

# Build rule for target.
audiowriter-static_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 audiowriter-static_automoc
.PHONY : audiowriter-static_automoc

# fast build rule for target.
audiowriter-static_automoc/fast:
	$(MAKE) -f src/CMakeFiles/audiowriter-static_automoc.dir/build.make src/CMakeFiles/audiowriter-static_automoc.dir/build
.PHONY : audiowriter-static_automoc/fast

#=============================================================================
# Target rules for targets named rtpserver_automoc

# Build rule for target.
rtpserver_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtpserver_automoc
.PHONY : rtpserver_automoc

# fast build rule for target.
rtpserver_automoc/fast:
	$(MAKE) -f src/CMakeFiles/rtpserver_automoc.dir/build.make src/CMakeFiles/rtpserver_automoc.dir/build
.PHONY : rtpserver_automoc/fast

#=============================================================================
# Target rules for targets named audiowriter_automoc

# Build rule for target.
audiowriter_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 audiowriter_automoc
.PHONY : audiowriter_automoc

# fast build rule for target.
audiowriter_automoc/fast:
	$(MAKE) -f src/CMakeFiles/audiowriter_automoc.dir/build.make src/CMakeFiles/audiowriter_automoc.dir/build
.PHONY : audiowriter_automoc/fast

#=============================================================================
# Target rules for targets named audioreader_automoc

# Build rule for target.
audioreader_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 audioreader_automoc
.PHONY : audioreader_automoc

# fast build rule for target.
audioreader_automoc/fast:
	$(MAKE) -f src/CMakeFiles/audioreader_automoc.dir/build.make src/CMakeFiles/audioreader_automoc.dir/build
.PHONY : audioreader_automoc/fast

#=============================================================================
# Target rules for targets named audiodecoder-static_automoc

# Build rule for target.
audiodecoder-static_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 audiodecoder-static_automoc
.PHONY : audiodecoder-static_automoc

# fast build rule for target.
audiodecoder-static_automoc/fast:
	$(MAKE) -f src/CMakeFiles/audiodecoder-static_automoc.dir/build.make src/CMakeFiles/audiodecoder-static_automoc.dir/build
.PHONY : audiodecoder-static_automoc/fast

#=============================================================================
# Target rules for targets named rtpaudiocommon_automoc

# Build rule for target.
rtpaudiocommon_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtpaudiocommon_automoc
.PHONY : rtpaudiocommon_automoc

# fast build rule for target.
rtpaudiocommon_automoc/fast:
	$(MAKE) -f src/CMakeFiles/rtpaudiocommon_automoc.dir/build.make src/CMakeFiles/rtpaudiocommon_automoc.dir/build
.PHONY : rtpaudiocommon_automoc/fast

#=============================================================================
# Target rules for targets named tdtoolbox_automoc

# Build rule for target.
tdtoolbox_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tdtoolbox_automoc
.PHONY : tdtoolbox_automoc

# fast build rule for target.
tdtoolbox_automoc/fast:
	$(MAKE) -f src/CMakeFiles/tdtoolbox_automoc.dir/build.make src/CMakeFiles/tdtoolbox_automoc.dir/build
.PHONY : tdtoolbox_automoc/fast

#=============================================================================
# Target rules for targets named audiocommon-static_automoc

# Build rule for target.
audiocommon-static_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 audiocommon-static_automoc
.PHONY : audiocommon-static_automoc

# fast build rule for target.
audiocommon-static_automoc/fast:
	$(MAKE) -f src/CMakeFiles/audiocommon-static_automoc.dir/build.make src/CMakeFiles/audiocommon-static_automoc.dir/build
.PHONY : audiocommon-static_automoc/fast

#=============================================================================
# Target rules for targets named rtpclient-static_automoc

# Build rule for target.
rtpclient-static_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtpclient-static_automoc
.PHONY : rtpclient-static_automoc

# fast build rule for target.
rtpclient-static_automoc/fast:
	$(MAKE) -f src/CMakeFiles/rtpclient-static_automoc.dir/build.make src/CMakeFiles/rtpclient-static_automoc.dir/build
.PHONY : rtpclient-static_automoc/fast

#=============================================================================
# Target rules for targets named rtpa-qclient_automoc

# Build rule for target.
rtpa-qclient_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtpa-qclient_automoc
.PHONY : rtpa-qclient_automoc

# fast build rule for target.
rtpa-qclient_automoc/fast:
	$(MAKE) -f src/CMakeFiles/rtpa-qclient_automoc.dir/build.make src/CMakeFiles/rtpa-qclient_automoc.dir/build
.PHONY : rtpa-qclient_automoc/fast

#=============================================================================
# Target rules for targets named mediainfo_automoc

# Build rule for target.
mediainfo_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mediainfo_automoc
.PHONY : mediainfo_automoc

# fast build rule for target.
mediainfo_automoc/fast:
	$(MAKE) -f src/CMakeFiles/mediainfo_automoc.dir/build.make src/CMakeFiles/mediainfo_automoc.dir/build
.PHONY : mediainfo_automoc/fast

#=============================================================================
# Target rules for targets named audiocodeccommon-static_automoc

# Build rule for target.
audiocodeccommon-static_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 audiocodeccommon-static_automoc
.PHONY : audiocodeccommon-static_automoc

# fast build rule for target.
audiocodeccommon-static_automoc/fast:
	$(MAKE) -f src/CMakeFiles/audiocodeccommon-static_automoc.dir/build.make src/CMakeFiles/audiocodeccommon-static_automoc.dir/build
.PHONY : audiocodeccommon-static_automoc/fast

#=============================================================================
# Target rules for targets named mediainfo-static_automoc

# Build rule for target.
mediainfo-static_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mediainfo-static_automoc
.PHONY : mediainfo-static_automoc

# fast build rule for target.
mediainfo-static_automoc/fast:
	$(MAKE) -f src/CMakeFiles/mediainfo-static_automoc.dir/build.make src/CMakeFiles/mediainfo-static_automoc.dir/build
.PHONY : mediainfo-static_automoc/fast

#=============================================================================
# Target rules for targets named rtpcommon-static_automoc

# Build rule for target.
rtpcommon-static_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtpcommon-static_automoc
.PHONY : rtpcommon-static_automoc

# fast build rule for target.
rtpcommon-static_automoc/fast:
	$(MAKE) -f src/CMakeFiles/rtpcommon-static_automoc.dir/build.make src/CMakeFiles/rtpcommon-static_automoc.dir/build
.PHONY : rtpcommon-static_automoc/fast

#=============================================================================
# Target rules for targets named rtpserver-static_automoc

# Build rule for target.
rtpserver-static_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtpserver-static_automoc
.PHONY : rtpserver-static_automoc

# fast build rule for target.
rtpserver-static_automoc/fast:
	$(MAKE) -f src/CMakeFiles/rtpserver-static_automoc.dir/build.make src/CMakeFiles/rtpserver-static_automoc.dir/build
.PHONY : rtpserver-static_automoc/fast

#=============================================================================
# Target rules for targets named audioencoder-static_automoc

# Build rule for target.
audioencoder-static_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 audioencoder-static_automoc
.PHONY : audioencoder-static_automoc

# fast build rule for target.
audioencoder-static_automoc/fast:
	$(MAKE) -f src/CMakeFiles/audioencoder-static_automoc.dir/build.make src/CMakeFiles/audioencoder-static_automoc.dir/build
.PHONY : audioencoder-static_automoc/fast

#=============================================================================
# Target rules for targets named rtpcommon_automoc

# Build rule for target.
rtpcommon_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtpcommon_automoc
.PHONY : rtpcommon_automoc

# fast build rule for target.
rtpcommon_automoc/fast:
	$(MAKE) -f src/CMakeFiles/rtpcommon_automoc.dir/build.make src/CMakeFiles/rtpcommon_automoc.dir/build
.PHONY : rtpcommon_automoc/fast

#=============================================================================
# Target rules for targets named rtpclient_automoc

# Build rule for target.
rtpclient_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtpclient_automoc
.PHONY : rtpclient_automoc

# fast build rule for target.
rtpclient_automoc/fast:
	$(MAKE) -f src/CMakeFiles/rtpclient_automoc.dir/build.make src/CMakeFiles/rtpclient_automoc.dir/build
.PHONY : rtpclient_automoc/fast

#=============================================================================
# Target rules for targets named audiocodeccommon_automoc

# Build rule for target.
audiocodeccommon_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 audiocodeccommon_automoc
.PHONY : audiocodeccommon_automoc

# fast build rule for target.
audiocodeccommon_automoc/fast:
	$(MAKE) -f src/CMakeFiles/audiocodeccommon_automoc.dir/build.make src/CMakeFiles/audiocodeccommon_automoc.dir/build
.PHONY : audiocodeccommon_automoc/fast

#=============================================================================
# Target rules for targets named audioreader-static_automoc

# Build rule for target.
audioreader-static_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 audioreader-static_automoc
.PHONY : audioreader-static_automoc

# fast build rule for target.
audioreader-static_automoc/fast:
	$(MAKE) -f src/CMakeFiles/audioreader-static_automoc.dir/build.make src/CMakeFiles/audioreader-static_automoc.dir/build
.PHONY : audioreader-static_automoc/fast

#=============================================================================
# Target rules for targets named audioencoder_automoc

# Build rule for target.
audioencoder_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 audioencoder_automoc
.PHONY : audioencoder_automoc

# fast build rule for target.
audioencoder_automoc/fast:
	$(MAKE) -f src/CMakeFiles/audioencoder_automoc.dir/build.make src/CMakeFiles/audioencoder_automoc.dir/build
.PHONY : audioencoder_automoc/fast

#=============================================================================
# Target rules for targets named qosmgr_automoc

# Build rule for target.
qosmgr_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qosmgr_automoc
.PHONY : qosmgr_automoc

# fast build rule for target.
qosmgr_automoc/fast:
	$(MAKE) -f src/CMakeFiles/qosmgr_automoc.dir/build.make src/CMakeFiles/qosmgr_automoc.dir/build
.PHONY : qosmgr_automoc/fast

#=============================================================================
# Target rules for targets named tdtoolbox-static_automoc

# Build rule for target.
tdtoolbox-static_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tdtoolbox-static_automoc
.PHONY : tdtoolbox-static_automoc

# fast build rule for target.
tdtoolbox-static_automoc/fast:
	$(MAKE) -f src/CMakeFiles/tdtoolbox-static_automoc.dir/build.make src/CMakeFiles/tdtoolbox-static_automoc.dir/build
.PHONY : tdtoolbox-static_automoc/fast

#=============================================================================
# Target rules for targets named audiocommon_automoc

# Build rule for target.
audiocommon_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 audiocommon_automoc
.PHONY : audiocommon_automoc

# fast build rule for target.
audiocommon_automoc/fast:
	$(MAKE) -f src/CMakeFiles/audiocommon_automoc.dir/build.make src/CMakeFiles/audiocommon_automoc.dir/build
.PHONY : audiocommon_automoc/fast

#=============================================================================
# Target rules for targets named audiodecoder_automoc

# Build rule for target.
audiodecoder_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 audiodecoder_automoc
.PHONY : audiodecoder_automoc

# fast build rule for target.
audiodecoder_automoc/fast:
	$(MAKE) -f src/CMakeFiles/audiodecoder_automoc.dir/build.make src/CMakeFiles/audiodecoder_automoc.dir/build
.PHONY : audiodecoder_automoc/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... package"
	@echo "... dist"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... mpegsound"
	@echo "... mpegsound-static"
	@echo "... mpegsound_automoc"
	@echo "... mpegsound-static_automoc"
	@echo "... rtpa-client"
	@echo "... rtpa-server"
	@echo "... qosmgr-static"
	@echo "... rtpaudioclient-static"
	@echo "... rtpa-vclient"
	@echo "... rtpaudioclient"
	@echo "... rtpaudioserver-static"
	@echo "... rtpaudioserver"
	@echo "... rtpaudiocommon-static"
	@echo "... audiowriter-static"
	@echo "... rtpserver"
	@echo "... audiowriter"
	@echo "... audioreader"
	@echo "... audiodecoder-static"
	@echo "... rtpaudiocommon"
	@echo "... tdtoolbox"
	@echo "... audiocommon-static"
	@echo "... rtpclient-static"
	@echo "... rtpa-qclient"
	@echo "... mediainfo"
	@echo "... audiocodeccommon-static"
	@echo "... mediainfo-static"
	@echo "... rtpcommon-static"
	@echo "... rtpserver-static"
	@echo "... audioencoder-static"
	@echo "... rtpcommon"
	@echo "... rtpclient"
	@echo "... audiocodeccommon"
	@echo "... audioreader-static"
	@echo "... audioencoder"
	@echo "... qosmgr"
	@echo "... tdtoolbox-static"
	@echo "... audiocommon"
	@echo "... audiodecoder"
	@echo "... rtpa-client_automoc"
	@echo "... rtpa-server_automoc"
	@echo "... qosmgr-static_automoc"
	@echo "... rtpaudioclient-static_automoc"
	@echo "... rtpa-vclient_automoc"
	@echo "... rtpaudioclient_automoc"
	@echo "... rtpaudioserver-static_automoc"
	@echo "... rtpaudioserver_automoc"
	@echo "... rtpaudiocommon-static_automoc"
	@echo "... audiowriter-static_automoc"
	@echo "... rtpserver_automoc"
	@echo "... audiowriter_automoc"
	@echo "... audioreader_automoc"
	@echo "... audiodecoder-static_automoc"
	@echo "... rtpaudiocommon_automoc"
	@echo "... tdtoolbox_automoc"
	@echo "... audiocommon-static_automoc"
	@echo "... rtpclient-static_automoc"
	@echo "... rtpa-qclient_automoc"
	@echo "... mediainfo_automoc"
	@echo "... audiocodeccommon-static_automoc"
	@echo "... mediainfo-static_automoc"
	@echo "... rtpcommon-static_automoc"
	@echo "... rtpserver-static_automoc"
	@echo "... audioencoder-static_automoc"
	@echo "... rtpcommon_automoc"
	@echo "... rtpclient_automoc"
	@echo "... audiocodeccommon_automoc"
	@echo "... audioreader-static_automoc"
	@echo "... audioencoder_automoc"
	@echo "... qosmgr_automoc"
	@echo "... tdtoolbox-static_automoc"
	@echo "... audiocommon_automoc"
	@echo "... audiodecoder_automoc"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

